### PR TITLE
Fix with absolute file path

### PR DESCRIPTION
**Pull request by theoneGUI**
Fixed the catalog bug.

Fixed a bug where it would fetch the product details forever on the individual product page.

### CODE REVIEW

**Comment by skhairunnesa** [comment]
@theoneGUI I see an error, when I click on the 'Login' option.

Screenshot 2024-05-03 at 8 55 47 AM

**Comment by theoneGUI** [comment]
Noted. I thought I fixed it. I'll work on it

**Comment by theoneGUI** [comment]
@skhairunnesa Please see the most recent changes for a fix for that bug, I apologize, I had a solution for it, but I implemented it everywhere except that one spot.

**Comment by skhairunnesa** [comment]
@theoneGUI No worries. I'll take a look. Please submit a pull request.

**Comment by skhairunnesa** [comment]
@theoneGUI A gentle reminder: waiting for your pull request!

**Pull request merged**
